apiVersion: v1
kind: Service
metadata:
  name: scaletestapp-service
  namespace: architecturehpa
  labels:
    app: scaletestapp
spec:
  selector:
    app: scaletestapp
  type: LoadBalancer
  ports:
  - name: http
    port: 8080           # Порт сервиса (внутри кластера)
    targetPort: 8080     # Порт контейнера
    protocol: TCP